import original from "@/data/guides.json";
import { setGuides, type CollectorGuide, type GuideSection } from "@/data/set-guides";

const additions: Record<string, { productIds: string[]; sections: GuideSection[] }> = {
  "etb-vs-booster-bundle": { productIds: ["destined-rivals-etb", "tcg-625670", "tcg-503313"], sections: [{ heading: "A practical break-even test", paragraphs: ["Set an accessory budget before comparing totals. If you would pay at most $8 for an ETB’s storage and promo together, a hypothetical $63 ETB with nine packs leaves $55, or $6.11 per pack, against that personal budget. It still does not beat a $36 six-pack purchase on pack cost. If you assign no value to the extras, use the unadjusted $7 figure instead.", "This is a willingness-to-pay exercise, not resale accounting. Never subtract the same accessory allowance from your collection cost or profit calculation unless an actual sale has occurred. The site’s per-pack figures intentionally allocate the full box price to packs so that the comparison remains reproducible."], bullets: ["Opening: compare exact pack contents and checkout totals.", "Keeping sealed: compare edition and packaging condition, not just packs.", "Buying as a gift: decide whether storage and accessories are useful before choosing the cheapest average."] }] },
  "pokemon-center-etb-vs-regular": { productIds: ["tcg-503313", "151-pc-etb", "prismatic-evolutions-etb", "tcg-593324"], sections: [{ heading: "Calculate the premium you are actually choosing", paragraphs: ["Try a sensitivity check rather than assigning the promo a guessed cash value. At a hypothetical $99 regular-ETB price, nine packs imply an $11 benchmark. An eleven-pack PC edition at $154 allocates $121 to packs on that basis, leaving $33 to justify for the edition. If the PC asking price rises to $198 while the regular price stays unchanged, that discretionary premium becomes $77. The additional packs have not changed; the amount you are choosing to pay for the distinction has.", "If a seller’s title says Pokémon Center but its description says nine packs or omits the edition, do not average the two records or take the more favorable price. Ask the seller which sealed product they will ship. A listing photo can be a stock image, and neither the image nor our reference record verifies that seller’s inventory."], bullets: ["Match the full edition name and language.", "Check the exact source specification, not a rule generalized from another set.", "Separate sealed-box comparisons from opened boxes and removed promos."] }] },
  "compare-price-per-pack": { productIds: ["destined-rivals-etb", "tcg-624679", "tcg-625677"], sections: [{ heading: "Mixed sets and discounts: two traps", paragraphs: ["A hypothetical $48 collection with eight packs averages $6. But if only four packs are from the set you wanted, that average does not mean you bought four wanted packs for $24. You spent $48 and received four other packs too. If those extras have no use to you, compare the whole $48 commitment with a product containing only the packs you want.", "Apply a discount once to the actual checkout total. For a $60 item with a $10 coupon and $5 shipping, the pre-tax total is $55. With ten packs, that is $5.50 each. Do not discount the headline price and then subtract the coupon again in your spreadsheet. Our two-purchase tool keeps item price, shipping, tax, and discount separate for this reason."], bullets: ["Use the same currency and tax treatment on both sides.", "Unknown pack count means no per-pack result, not zero.", "An average is not an expected value for the cards you will pull."] }] },
  "buying-sealed-pokemon-online": { productIds: ["tcg-624679", "tcg-625677"], sections: [{ heading: "A thirty-second listing mismatch check", paragraphs: ["Read the quantity line before the photograph. A listing titled Destined Rivals booster box might offer a single pack in a dropdown, while the image shows a display. Compare the selected option and checkout quantity with the 36-pack display specification. A case is a different quantity again; do not enter its entire asking price against one box’s market estimate.", "If the description contradicts the title, stop before paying. A useful message is: ‘Can you confirm that this selected option is one factory-sealed English display containing 36 packs, with no contents removed?’ The answer still does not guarantee authenticity, but it gives you a specific representation to preserve with the order."], bullets: ["Save the selected variant, contents description, and checkout total.", "Check seller-specific return terms before purchase, not after opening.", "Treat preorder dispatch dates as promises by that seller, not proof of available stock.", "Do not buy because a price badge alone looks favorable; it does not evaluate the seller."] }] },
  "retail-reference-vs-listing-price": { productIds: ["destined-rivals-etb", "tcg-503313"], sections: [{ heading: "Why a gross spread is not take-home profit", paragraphs: ["Suppose a hypothetical box has a $50 purchase cost and an $80 resale estimate. The gross spread is $30, or 60% of the purchase price. With a hypothetical 13.25% selling fee, $0.30 fixed fee, and $5 seller-paid shipping, proceeds become $64.10 and profit becomes $14.10 before purchase tax or other costs. Those are different answers to different questions.", "In the buy check, inspect the active fee and shipping settings instead of assuming this example matches your marketplace. Enter your actual purchase price; the historical retail reference is only a starting scenario. A lower realized sale price, returns, supplies, or an unsold item can erase the modeled margin. No estimate here is a guaranteed exit price."], bullets: ["Retail reference: context, not an available offer.", "Market snapshot: a dated source estimate, not guaranteed proceeds.", "Your paid amount: the cost basis that matters for your own collection.", "Sold amount: record the actual transaction and costs, not the earlier estimate."] }] },
};

export const guides: CollectorGuide[] = [
  ...setGuides,
  ...original.map(guide => ({ ...guide, updated: "2026-09-27", productIds: additions[guide.slug].productIds,
    sections: [...guide.sectionHeadings.map((heading, i) => ({ heading, paragraphs: guide.paragraphs.slice(i * 2, i * 2 + 2) })), ...additions[guide.slug].sections],
  })),
];

export function editorialDate(date: string) { return new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`)); }
